// Code generated by protoc-gen-go. DO NOT EDIT.
// source: multiple1.proto

// test to make sure that multiple proto files in one package works

package multiple

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Msg1 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg1) Reset()         { *m = Msg1{} }
func (m *Msg1) String() string { return proto.CompactTextString(m) }
func (*Msg1) ProtoMessage()    {}
func (*Msg1) Descriptor() ([]byte, []int) {
	return fileDescriptor_78303a5590f73d4e, []int{0}
}

func (m *Msg1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg1.Unmarshal(m, b)
}
func (m *Msg1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg1.Marshal(b, m, deterministic)
}
func (m *Msg1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg1.Merge(m, src)
}
func (m *Msg1) XXX_Size() int {
	return xxx_messageInfo_Msg1.Size(m)
}
func (m *Msg1) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg1.DiscardUnknown(m)
}

var xxx_messageInfo_Msg1 proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Msg1)(nil), "twirptest.multiple.Msg1")
}

func init() { proto.RegisterFile("multiple1.proto", fileDescriptor_78303a5590f73d4e) }

var fileDescriptor_78303a5590f73d4e = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x2d, 0xcd, 0x29,
	0xc9, 0x2c, 0xc8, 0x49, 0x35, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2a, 0x29, 0xcf,
	0x2c, 0x2a, 0x28, 0x49, 0x2d, 0x2e, 0xd1, 0x83, 0x49, 0x29, 0xb1, 0x71, 0xb1, 0xf8, 0x16, 0xa7,
	0x1b, 0x1a, 0x39, 0x71, 0xb1, 0x04, 0x97, 0x25, 0x1b, 0x0a, 0x59, 0x71, 0xb1, 0x04, 0xa7, 0xe6,
	0xa5, 0x08, 0x49, 0xe8, 0x61, 0x2a, 0xd6, 0x03, 0xa9, 0x94, 0xc2, 0x29, 0xe3, 0xc4, 0x15, 0xc5,
	0x01, 0x13, 0x48, 0x62, 0x03, 0x5b, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x53, 0x53, 0xf0,
	0xe4, 0x85, 0x00, 0x00, 0x00,
}
